name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Set env var
      run: echo "OPEN_AI_ORG=${{ secrets.OPEN_AI_ORG }}" >> $GITHUB_ENV
    - name: Set env var
      run: echo "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> $GITHUB_ENV
    - name: Run tests
      run: cargo test --verbose
